Models/Business.cs
using System.ComponentModel.DataAnnotations;

namespace ShopCovid19MCV.Models
{
    public class Business
    {
        public int Id { get; set; }
        public string City { get; set; }
        
        [Required]
        public string BusinessName { get; set; }
        public string ContactName { get; set; }
        
        [Required]
        public string Email { get; set; }
        public string PersonalPhone { get; set; }
        public string BusinessPhone { get; set; }
        public string Url { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public bool GiftCards { get; set; }
        public bool Online { get; set; }
        public bool Curbside { get; set; }
        public bool Delivery { get; set; }
        public bool PIF { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ShopCovid19MCV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NonProfit.cs
using System.ComponentModel.DataAnnotations;

namespace ShopCovid19MCV.Models
{
    public class NonProfit
    {
        public int Id { get; set; }
        public string City { get; set; }
        [Required]
        public string NonProfitName { get; set; }
        public string MailingAddress { get; set; }
        public string ContactName { get; set; }
        
        [Required]
        public string Email { get; set; }
        public string PersonalPhone { get; set; }
        public string NonProfitPhone { get; set; }
        public string Url { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
    }
}

Models/PayItForward.cs
using System.ComponentModel.DataAnnotations;

namespace ShopCovid19MCV.Models
{
    public class PayItForward
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        public string Phone { get; set; }
        public int GiftCardAmount { get; set; }
        [Required]
        public int BusinessId { get; set; }
        [Required]
        public int NonProfitId { get; set; }
    }
}

Models/PayItForwardViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ShopCovid19MCV.Models
{
    public class PayItForwardViewModel
    {
        public PayItForward payItForward { get; set; }
        public List<SelectListItem> LuNp { get; set; }
        public string BusinessName { get; set; }
        public int BusinessId { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopCovid19MCV.Models;
using ShopCovid19MCV.Data;
using Microsoft.EntityFrameworkCore;

namespace ShopCovid19MCV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Businesses.ToListAsync());
        }  
        public async Task<IActionResult> PayItForward()
        {
            return View(await _context.NonProfits.ToListAsync());
        }


        // private readonly ILogger<HomeController> _logger;

        // public HomeController(ILogger<HomeController> logger)
        // {
        //     _logger = logger;
        // }

        // public IActionResult Index()
        // {
        //     return View();
        // }

        // public IActionResult Privacy()
        // {
        //     return View();
        // }

        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        // }
    }
}

Controllers/SubmissionsController.cs
using System.Net.Mime;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopCovid19MCV.Models;
using ShopCovid19MCV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ShopCovid19MCV.Controllers
{
    public class SubmissionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SubmissionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult AddBusiness()
        {
            return View();
        }        
        public IActionResult AddNonProfit()
        {
            return View();
        }        
        [HttpGet]
        public IActionResult SubmitPayItForward(int id)
        {
            var biz = _context.Businesses.SingleOrDefault(x => x.Id == id);
            var lunp = _context.NonProfits.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.NonProfitName}).ToList();

            var viewModel = new PayItForwardViewModel
            {
                BusinessId = biz.Id,
                BusinessName = biz.BusinessName,
                LuNp = lunp
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddBusiness(Business business)
        {
            _context.Businesses.Add(business);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        public IActionResult AddNonProfit(NonProfit nonprofit)
        {
            _context.NonProfits.Add(nonprofit);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult SubmitPayItForward(PayItForward payitforward)
        {
            _context.PayItForwards.Add(payitforward);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

    }
}

Views/Home/Index.cshtml
@model IEnumerable<ShopCovid19MCV.Models.Business>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

<div class="text-center">
    <h4><a asp-controller="Submissions" asp-action="AddBusiness">Add Business</a></h4>
    <h4><a asp-controller="Submissions" asp-action="AddNonProfit">Add Non-Profit</a></h4>
</div>

<div class="text-center mb-5">
    <h4><a asp-controller="Home" asp-action="PayItForward">View Pay It Forward Directory</a></h4>
</div>


    <table id="businessTable" style="width: 100%;">
        <thead>
            <th>Business</th>
            <th>Phone</th>
            <th>Social</th>
            <th>Gift Cards</th>
            <th>Online</th>
            <th>Curbside</th>
            <th>Delivery</th>
            <th>Pay It Forward</th>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor( modelx => x.BusinessName)
                </td>                
                <td>
                    @Html.DisplayFor( modelx => x.BusinessPhone)
                </td>
                <td>
                    @Html.DisplayFor( modelx => x.BusinessPhone)
                </td>                
                <td>
                    @Html.DisplayFor( modelx => x.GiftCards)
                </td>                
                <td>
                    @Html.DisplayFor( modelx => x.Online)
                </td>                
                <td>
                    @Html.DisplayFor( modelx => x.Curbside)
                </td>
                <td>
                    @Html.DisplayFor( modelx => x.Delivery)
                </td>
                @if( x.PIF == true )
                {
                <td>
                    <a asp-controller="Submissions" asp-action="SubmitPayItForward" asp-route-Id="@x.Id">Pay It Forward</a>
                </td>
                }else
                {
                <td>
                    @Html.DisplayFor( modelx => x.PIF)
                </td>
                }
                
            </tr>  
            }
        </tbody>
    </table>
<script>
    $(document).ready( function () {
    $('#businessTable').DataTable();
} );
</script>

Views/Home/PayItForward.cshtml
@model IEnumerable<ShopCovid19MCV.Models.NonProfit>

@{
    ViewData["Title"] = "Pay It Forward";
}

<div class="text-center">
    <h1 class="display-4">Pay It Forward Home Page</h1>
    <h4><a asp-controller="Home" asp-action="Index">Back to IShopTally</a></h4>
</div>

<div class="text-center">
    <h4><a asp-controller="Submissions" asp-action="AddNonProfit">Add Non-Profit</a></h4>
</div>


    <table id="nonprofitTable" class="text-center" >
        <thead>
            <th>Non-Profits</th>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor( modelx => x.NonProfitName)
                </td>                
            </tr>  
            }
        </tbody>
    </table>
<script>
    $(document).ready( function () {
    $('#nonprofitTable').DataTable();
} );
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopCovid19MCV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopCovid19MCV</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @* <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopCovid19MCV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Submissions/AddBusiness.cshtml
@model ShopCovid19MCV.Models.Business

@{
    ViewData["Title"] = "Add Business";
}

<div class="text-center">
    <h2>Add your Business</h2>
    <p><a asp-controller="Home" asp-action="Index">Return to Home Page</a></p>
</div>

<form asp-controller="Submissions" asp-action="AddBusiness" method="POST">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="City" value="Denver" />
    <div class="row">
        <div class="col-md-6">
            <div class="row">

                <h4 class="col-12">Information</h4>
                <div class="col-6 mb-2">
                    <label asp-for="BusinessName" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="BusinessName" />
                    <span asp-validation-for="BusinessName" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="ContactName" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="ContactName" />
                    <span asp-validation-for="ContactName" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Email" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="PersonalPhone"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="PersonalPhone" />
                    <span asp-validation-for="PersonalPhone" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="BusinessPhone" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="BusinessPhone" />
                    <span asp-validation-for="BusinessPhone" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Url" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Url" />
                    <span asp-validation-for="Url" class="text-danger"></span>
                </div>

                <h4 class="col-12">Social</h4>
                <p class="col-12">The full url. (ex: https://www.instagram.com/swellcoin/)</p>
                <div class="col-6 mb-2">
                    <label asp-for="Facebook" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Facebook" />
                    <span asp-validation-for="Facebook" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Instagram" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Instagram" />
                    <span asp-validation-for="Instagram" class="text-danger"></span>
                </div>
                <h4 class="col-12">What are you offering?</h4> 
                <div class="col-6 mb-2">
                    <label asp-for="GiftCards" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="GiftCards" />
                    <span asp-validation-for="GiftCards" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Online" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Online" />
                    <span asp-validation-for="Online" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Curbside" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Curbside" />
                    <span asp-validation-for="Curbside" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Delivery" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Delivery" />
                    <span asp-validation-for="Delivery" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="PIF" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="PIF" />
                    <span asp-validation-for="PIF" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Submissions/AddNonProfit.cshtml
@model ShopCovid19MCV.Models.NonProfit

@{
    ViewData["Title"] = "Add NonProfit";
}

<div class="text-center">
    <h2>Add your NonProfit</h2>
    <p><a asp-controller="Home" asp-action="Index">Return to Home Page</a></p>
</div>

<form asp-controller="Submissions" asp-action="AddNonProfit" method="POST">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="City" value="Denver" />
    <div class="row">
        <div class="col-md-6">
            <div class="row">

                <h4 class="col-12">Information</h4>
                <div class="col-6 mb-2">
                    <label asp-for="NonProfitName" ></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="NonProfitName" class="form-control" />
                    <span asp-validation-for="NonProfitName" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="MailingAddress" ></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="MailingAddress" />
                    <span asp-validation-for="MailingAddress" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="ContactName" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="ContactName" />
                    <span asp-validation-for="ContactName" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Email" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="PersonalPhone"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="PersonalPhone" />
                    <span asp-validation-for="PersonalPhone" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Url" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Url" />
                    <span asp-validation-for="Url" class="text-danger"></span>
                </div>
                <h4 class="col-12">Social</h4>
                <p class="col-12">The full url. (ex: https://www.instagram.com/swellcoin/)</p>
                <div class="col-6 mb-2">
                    <label asp-for="Facebook" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Facebook" />
                    <span asp-validation-for="Facebook" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="Instagram" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="Instagram" />
                    <span asp-validation-for="Instagram" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Submissions/SubmitPayItForward.cshtml
@model ShopCovid19MCV.Models.PayItForwardViewModel

@{
    ViewData["Title"] = "Submit Pay It Forward";
}

<div class="text-center">
    <h2>Submit Pay It Forward</h2>
    <p><a asp-controller="Home" asp-action="Index">Return to IShopTally Page</a></p>
</div>

<form asp-controller="Submissions" asp-action="SubmitPayItForward" method="POST">
    <input type="hidden" asp-for="payItForward.Id" />
    <div class="row">
        <div class="col-md-6">
            <div class="row">

                <h4 class="col-12">Information</h4>
                <div class="col-6 mb-2">
                    <label asp-for="payItForward.Name" ></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="payItForward.Name" class="form-control" />
                    <span asp-validation-for="payItForward.Name" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="payItForward.Email" ></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="payItForward.Email" />
                    <span asp-validation-for="payItForward.Email" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="payItForward.Phone" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="payItForward.Phone" />
                    <span asp-validation-for="payItForward.Phone" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="payItForward.GiftCardAmount" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="payItForward.GiftCardAmount" class="form-control" />
                    <span asp-validation-for="payItForward.GiftCardAmount" class="text-danger"></span>
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="BusinessName"></label>
                </div>
                <div class="col-6 mb-2">
                    <input asp-for="payItForward.BusinessId" type="hidden" value="@Model.BusinessId"/>
                    <input asp-for="BusinessName" class="form-control" disabled />
                </div> 
                <div class="col-6 mb-2">
                    <label asp-for="payItForward.NonProfitId" class="required"></label>
                </div>
                <div class="col-6 mb-2">
                    <select asp-for="payItForward.NonProfitId" asp-items="Model.LuNp" class="form-control"></select>
                    <span asp-validation-for="payItForward.NonProfitId" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>